### ISSUE TITLE
Freezes on command.send()

### ISSUE THREAD

**Issue by MySixSenses** [Iapetus-11/aio-mc-rcon#2]
```py
async def exec_command(command: str):
    rconClient = Client("192.168.1.18", 25575, "passw")
    print("test")
    await rconClient.connect()
    print("test")
    response = await client.send_cmd(command)
    print("test")
    await rconClient.close()
    print("test")
    return response
```
Freezes after printing test twice.

**Comment by Iapetus-11** [comment]
I don't think this is an issue with the library, but I'll investigate anyways. What type of server / server software are you using, and can you send me the server.properties file (remember to remove the rcon.password from it)? Also send the OS you're running the code on, and any other relevant information like are you using something like uvloop?

**Comment by MySixSenses** [comment]
Server is Paper
server.properties: https://gist.github.com/MySixSenses/3a77fbdc2261cd5dc5cbc8ad20a64de0
OS: Raspbian/Debian

**Comment by Iapetus-11** [comment]
What version of paper? (Like Minecraft version, like 1.17 or 1.16.5, etc...)

**Comment by MySixSenses** [comment]
1.16.5

**Comment by Iapetus-11** [comment]
Weird, this library worked just fine when tested on my old 1.16.5 paper server, and still works on my spigot 1.17 server. Maybe double check that you don't have any firewall or something similar in place, I'm not sure what else to check.

**Comment by Iapetus-11** [comment]
Would you mind showing me the entire program?

**Comment by Iapetus-11** [comment]
I just doublechecked that it worked using my Discord bot, [Villager Bot](https://github.com/Iapetus-11/Villager-Bot). I tested it on a spigot 1.17 server, using the latest version (3.0.2) of this library. Villager Bot runs on Raspberry Pi OS on a Raspberry Pi 4, so I'm pretty sure it's the server you have set up.

**Comment by MySixSenses** [comment]
Code here: https://gist.github.com/MySixSenses/24bc53b0b09b6d17093311ad764492d1
I'll check firewall.

**Comment by Iapetus-11** [comment]
I looked at the code and everything seems fine. If i *had* to be a problem with your code I'd try temporarily removing the import for the other rcon library just to see if that fixes anything.

**Comment by MySixSenses** [comment]
An even weirder thing is that the script doesn't even seem to execute send_command(). Inserting print("testing') at the start of send_command() doesn't print.

**Comment by MySixSenses** [comment]
Sorry for being an idiot, but I realized that the rcon Client is named rconClient, while Client.send uses Client.
